"""Account code and role values for the company chart of accounts."""

from __future__ import annotations

from enum import StrEnum


class AccountRole(StrEnum):
    ASSET = "ASSET"
    LIABILITY = "LIABILITY"
    EQUITY = "EQUITY"
    REVENUE = "REVENUE"
    EXPENSE = "EXPENSE"
    OTHER = "OTHER"
    ASSET_COST_ACCOUNT = "ASSET_COST_ACCOUNT"
    DEPRECIATION_EXPENSE_ACCOUNT = "DEPRECIATION_EXPENSE_ACCOUNT"
    ACCUMULATED_DEPRECIATION_ACCOUNT = "ACCUMULATED_DEPRECIATION_ACCOUNT"
    IMPAIRMENT_EXPENSE_ACCOUNT = "IMPAIRMENT_EXPENSE_ACCOUNT"
    PROVISION_ACCOUNT = "PROVISION_ACCOUNT"
    INVENTORY_ACCOUNT = "INVENTORY_ACCOUNT"
    COST_OF_SALES_ACCOUNT = "COST_OF_SALES_ACCOUNT"
    ACCRUAL_ACCOUNT = "ACCRUAL_ACCOUNT"
    DEFERRAL_ACCOUNT = "DEFERRAL_ACCOUNT"


__all__ = ["AccountRole"]
