BALANCE_LEFT=[("AD","IMMOBILISATIONS INCORPORELLES"),("AF","Brevets, licences, logiciels et droits similaires"),("AG","Fonds commercial et droit au bail"),
("AI","IMMOBILISATIONS CORPORELLES"),("AJ","Terrains"),("AK","Bâtiments"),("AL","Aménagements, agencements et installations"),
("AM","Matériel, mobilier et actifs biologiques"),("AN","Matériel de transport"),("AP","AVANCES ET ACOMPTES VERSES SUR IMMOBILISATIONS"),
("AQ","IMMOBILISATIONS FINANCIERES"),("AS","Autres immobilisations financières"),("AZ","TOTAL ACTIF IMMOBILISE"),("BA","ACTIF CIRCULANT HAO"),
("BB","STOCKS ET ENCOURS"),("BG","CREANCES ET EMPLOIS ASSIMILES"),("BH","Fournisseurs avances versées"),("BI","Clients"),("BJ","Autres créances"),
("BK","TOTAL ACTIF CIRCULANT"),("BS","Banques, chèques postaux, caisse et assimilés"),("BT","TOTAL TRESORERIE ACTIF"),
("BU","Ecart de conversion-Actif"),("BZ","TOTAL GENERAL")]
BALANCE_RIGHT=[("CA","Capital"),("CB","Apporteurs capital non appelé (-)"),("CD","Ecarts de réévaluation"),("CE","Réserves indisponibles"),
("CF","Report à nouveau (+ ou -)"),("CG","Résultat net de l'exercice (bénéfice + ou perte -)"),("CH","Subventions d'investissement"),
("CJ","Provisions réglementées"),("CP","TOTAL CAPITAUX PROPRES ET RESSOURCES ASSIMILEES"),("DA","Emprunts et dettes financières diverses"),
("DC","Provisions pour risques et charges"),("DD","TOTAL DETTES FINANCIERES ET RESSOURCES ASSIMILEES"),("DF","TOTAL RESSOURCES STABLES"),
("DH","Dettes circulantes HAO"),("DI","Clients, avances reçues"),("DJ","Fournisseurs d'exploitation"),("DK","Dettes fiscales et sociales"),
("DM","Autres dettes"),("DN","Provisions pour risques a court terme"),("DP","TOTAL PASSIF CIRCULANT"),
("DR","Banques, établissements financiers et crédits de trésorerie"),("DT","TOTAL TRESORERIE PASSIF"),
("DV","Ecart de conversion-Passif"),("DZ","TOTAL GENERAL")]
INCOME=[("TA","Ventes de marchandises"),("RA","Achats de marchandises"),("RB","Variation de stocks de marchandises"),("XA","MARGE COMMERCIALE"),
("TB","Ventes de produits fabriqués"),("TC","Travaux, services vendus"),("TD","Produits accessoires"),("XB","CHIFFRE D'AFFAIRES"),
("TF","Production immobilisée"),("TH","Autres produits"),("TI","Transferts de charges d'exploitation"),("RC","Achats de matières premières et fournitures liées"),
("RD","Variation de stocks de matières premières et fournitures liées"),("RE","Autres achats"),("RF","Variation de stocks d’autres approvisionnements"),
("RG","Transports"),("RH","Services extérieurs"),("RI","Impôts et taxes"),("RJ","Autres charges"),("XC","VALEUR AJOUTEE"),("RK","Charges de personnel"),
("XD","EXCEDENT BRUT D'EXPLOITATION"),("RL","Dotations aux amortissements aux provisions et dépréciations"),("XE","RESULTAT D'EXPLOITATION"),
("TK","Revenus financiers et assimilés"),("RM","Frais financiers et charges assimilés"),("XF","RESULTAT FINANCIER"),
("XG","RESULTAT DES ACTIVITES ORDINAIRES"),("TN","Produits des cessions d'immobilisations"),("TO","Autres Produits HAO"),
("RO","Valeurs comptables des cessions d'immobilisations"),("XH","RESULTAT HORS ACTIVITES ORDINAIRES"),("RS","Impôts sur le résultat"),("XI","RESULTAT NET")]
TFT=[("ZA","Trésorerie nette au 1er janvier"),("FA","Capacité d'Autofinancement Globale (CAFG)"),("FB","Variations de l'actif circulant HAO"),
("FC","Variation des stocks"),("FD","Variation des créances et emplois assimilés"),("FE","Variation du passif circulant"),
("ZB","Flux de trésorerie provenant des activités opérationnelles"),("FF","Décaissements liés aux acquisitions d'immobilisations incorporelles"),
("FG","Décaissements liés aux acquisitions d'immobilisations corporelles"),("FH","Décaissements liés aux acquisitions d'immobilisations financières"),
("FI","Encaissements liés aux cessions d’immobilisations incorporelles et corporelles"),("FJ","Encaissements liés aux cessions d’immobilisations financières"),
("ZC","Flux de trésorerie provenant des opérations d’investissement"),("FK","Augmentations de capital par apports nouveaux"),("FL","Subventions d'investissement"),
("FN","Distribution de dividendes"),("ZD","Flux de trésorerie provenant des capitaux propres"),("FO","Emprunts"),
("FQ","Remboursements des emprunts et autres dettes financières"),("ZE","Flux de Trésorerie provenant des capitaux étrangers"),
("ZF","Flux de trésorerie provenant des activités de financement"),("ZF","VARIATION DE LA TRÉSORERIE NETTE DE LA PÉRIODE"),("ZH","Trésorerie nette au 31 Décembre")]
NOTES=[("NOTE 1","DETTES GARANTIES PAR DES SURETES REELLES"),("NOTE 2","INFORMATIONS OBLIGATOIRES"),("NOTE 3A","IMMOBILISATION BRUTE"),
("NOTE 3B","BIENS PRIS EN LOCATION ACQUISITION"),("NOTE 3C","IMMOBILISATIONS : AMORTISSEMENTS"),("NOTE 3D","IMMOBILISATIONS : PLUS-VALUES ET MOINS VALUE DE CESSION"),
("NOTE 3E","INFORMATIONS SUR LES REEVALUATIONS EFFECTUEES PAR L'ENTITE"),("NOTE 3F","TABLEAU D'ETALEMENT DES CHARGES IMMOBILISEES"),
("NOTE 4","IMMOBILISATIONS FINANCIERES"),("NOTE 5","ACTIF CIRCULANT ET DETTES CIRCULANTES HAO"),("NOTE 6","STOCKS ET ENCOURS"),("NOTE 7","CLIENTS"),
("NOTE 8","AUTRES CREANCES"),("NOTE 9","TITRES DE PLACEMENT"),("NOTE 10","VALEURS A ENCAISSER"),("NOTE 11","DISPONIBILITES"),
("NOTE 12","ECARTS DE CONVERSION ET TRANSFERTS DE CHARGES"),("NOTE 13","CAPITAL : VALEUR NOMINALE DES ACTIONS OU PARTS"),("NOTE 14","PRIMES ET RESERVES"),
("NOTE 15A","SUBVENTIONS ET PROVISIONS REGLEMENTEES"),("NOTE 15B","AUTRES FONDS PROPRES"),("NOTE 16A","DETTES FINANCIERES ET RESSOURCES ASSIMILEES"),
("NOTE 16B","ENGAGEMENTS DE RETRAITE ET AVANTAGES ASSIMILES (METHODE ACTUARIELLE)"),("NOTE 16B bis","ENGAGEMENTS DE RETRAITE ET AVANTAGES ASSIMILES (METHODE ACTUARIELLE)"),
("NOTE 16C","ACTIFS ET PASSIFS EVENTUELS"),("NOTE 17","FOURNISSEURS D'EXPLOITATION"),("NOTE 18","DETTES FISCALES ET SOCIALES"),
("NOTE 19","AUTRES DETTES ET PROVISIONS POUR RISQUES A COURT TERME"),("NOTE 20","BANQUES, CREDIT D'ESCOMPTE ET DE TRESORERIE"),
("NOTE 21","CHIFFRE D'AFFAIRES ET AUTRES PRODUITS"),("NOTE 22","ACHATS"),("NOTE 23","TRANSPORTS"),("NOTE 24","SERVICES EXTERIEURS"),
("NOTE 25","IMPOTS ET TAXES"),("NOTE 26","AUTRES CHARGES"),("NOTE 27A","CHARGES DE PERSONNEL"),("NOTE 27B","EFFECTIFS, MASSE SALARIALE ET PERSONNEL EXTERIEUR"),
("NOTE 28","PROVISIONS ET DEPRECIATIONS INSCRITES AU BILAN"),("NOTE 29","CHARGES ET REVENUS FINANCIERS"),("NOTE 30","AUTRES CHARGES ET PRODUITS HAO"),
("NOTE 31","REPARTITION DU RESULTAT ET AUTRES ELEMENTS CARACTERISTIQUES DES CINQ DERNIERS EXERCICES"),("NOTE 32","PRODUCTION DE L'EXERCICE"),
("NOTE 33","ACHATS DESTINES A LA PRODUCTION"),("NOTE 34","FICHE DE SYNTHESE DES PRINCIPAUX INDICATEURS FINANCIERS"),
("NOTE 35","LISTE DES INFORMATIONS SOCIALES, ENVIRONNEMENTALES ET SOCIETALES A FOURNIR"),("NOTE 36","TABLES DES CODES")]

def model(statement_id,name,page,rows,side=None):
    return {"statement_id":statement_id,"name":name,"source_kind":"Application 127 model example",
            "source":{"document_id":"syscohada-guide-2017-md","page_pdf":page,"section":"APPLICATION 127"},
            "lines":[{"line_id":f"{statement_id}:line:{i:03d}","source_ref_code":r,"label_source":l,"side":side} for i,(r,l) in enumerate(rows,1)]}

def build_reporting():
    balance={"statement_id":"syscohada2017:statement:balance-model","name":"Bilan - modèle Application 127","source_kind":"Application 127 model example",
             "source":{"document_id":"syscohada-guide-2017-md","page_pdf":356,"section":"BILAN AU 31 DECEMBRE N"},
             "lines":[*({"line_id":f"balance:asset:{i:03d}","source_ref_code":r,"label_source":l,"side":"asset"} for i,(r,l) in enumerate(BALANCE_LEFT,1)),
                      *({"line_id":f"balance:liability:{i:03d}","source_ref_code":r,"label_source":l,"side":"liability"} for i,(r,l) in enumerate(BALANCE_RIGHT,1))]}
    rules=[
      {"rule_id":"syscohada-reporting:bilan:classes","statement":"balance","source_page_pdf":329,
       "source_text":"Classe 2 à l'actif immobilisé; classe 1 au passif stable; soldes débiteurs classes 3/4 et 5 à l'actif; soldes créditeurs classes 4 et 5 au passif.",
       "selectors":{"asset_immobilized":["2"],"equity_and_financial_debt":["1"],"current_asset_debit":["3","4"],"cash_asset_debit":["5"],"current_liability_credit":["4"],"cash_liability_credit":["5"]}},
      {"rule_id":"syscohada-reporting:bilan:contra","statement":"balance","source_page_pdf":329,
       "source_text":"Les amortissements 28 et dépréciations 29 à 59 figurent à l'actif en soustraction.","selectors":{"contra_asset_prefixes":["28","29","39","49","59"]}},
      {"rule_id":"syscohada-reporting:income:margin","statement":"income","source_page_pdf":331,
       "source_text":"Marge commerciale: TA (701), RA (601), RB (6031).","post_mappings":{"TA":["701"],"RA":["601"],"RB":["6031"]}},
      {"rule_id":"syscohada-reporting:income:turnover","statement":"income","source_page_pdf":331,
       "source_text":"Chiffre d'affaires: postes TA à TD, comptes 70 ventes.","post_mappings":{"TA_TD":["70"]}},
      {"rule_id":"syscohada-reporting:income:value-added","statement":"income","source_page_pdf":331,
       "source_text":"Valeur ajoutée: 73,72,71,75,781; achats 601 à 608; variations 603; consommations 61 à 65.",
       "post_mappings":{"products":["73","72","71","75","781"],"purchases":["601","602","603","604","605","608"],"intermediate_consumption":["61","62","63","64","65"]}},
      {"rule_id":"syscohada-reporting:income:ebe","statement":"income","source_page_pdf":331,"source_text":"EBE après RK compte 66.","post_mappings":{"RK":["66"]}},
      {"rule_id":"syscohada-reporting:income:operating-result","statement":"income","source_page_pdf":331,"source_text":"TJ comptes 791,798,799 et RL comptes 681,691.","post_mappings":{"TJ":["791","798","799"],"RL":["681","691"]}},
      {"rule_id":"syscohada-reporting:income:financial-result","statement":"income","source_page_pdf":331,"source_text":"TK à TM: 77,797,787; RM/RN:67,697.","post_mappings":{"TK_TM":["77","797","787"],"RM_RN":["67","697"]}},
      {"rule_id":"syscohada-reporting:income:hao-source-conflict","statement":"income","source_page_pdf":331,
       "source_text":"Le narratif nomme TN/TO pour 82,84,86,88 et RM/RN pour 81,83,85, tandis que le modèle utilise RO notamment.",
       "post_mappings":{"TN_TO":["82","84","86","88"],"source_named_charge_posts":["RM","RN"],"charge_accounts":["81","83","85"]},"evaluation_status":"blocked_source_conflict"},
      {"rule_id":"syscohada-reporting:tft:components","statement":"cashflow","source_page_pdf":333,
       "source_text":"ZA début; FA-FE opérationnel; FF-FJ investissement; FK-FN capitaux propres; FO-FQ capitaux étrangers; ZH fin.",
       "post_groups":{"opening":["ZA"],"operating":["FA","FB","FC","FD","FE"],"investing":["FF","FG","FH","FI","FJ"],"equity_financing":["FK","FL","FN"],"debt_financing":["FO","FQ"],"closing":["ZH"]}}
    ]
    return {"standard_id":"ohada-syscohada","edition":"2017","dataset_layer":"v3_reporting",
            "source_scope":{"application_127_is_example":True,"guide_states_zero_or_nonapplicable_rows_may_be_removed":True,
                            "official_exhaustive_post_account_correspondence_table_available_in_bundle":False,
                            "missing_source":"Plan comptable général OHADA Titre IX chapitre 7 - tables Postes/Comptes"},
            "statement_types":[{"type":"balance","source_post_range":"AD à DZ"},{"type":"income","source_post_range":"RA à TO et XA à XI"},
                               {"type":"cashflow","source_post_range":"FA à FQ et ZA à ZH"},{"type":"notes","source_post_range":"non lettrés"}],
            "model_example":{"balance":balance,"income":model("syscohada2017:statement:income-model","Compte de résultat - modèle Application 127",357,INCOME),
                             "cashflow":model("syscohada2017:statement:cashflow-model","Tableau des flux de trésorerie - modèle Application 127",358,TFT),
                             "notes":[{"note_id":f"syscohada2017:note:{i:02d}","reference":r,"label_source":l,"source_page_pdf":355} for i,(r,l) in enumerate(NOTES,1)]},
            "source_supported_narrative_rules":rules,
            "observations":[{"type":"duplicate_source_ref_code","statement":"cashflow","source_ref_codes":["ZF"],"source_page_pdf":358,"status":"preserved_source_conflict"},
                            {"type":"missing_official_correspondence_table","status":"source_scope_gap"}],
            "statistics":{"statement_types":4,"balance_model_lines":48,"income_model_lines":34,"cashflow_model_lines":23,"notes":46,
                          "narrative_rules":len(rules),"source_observations":2}}
