from __future__ import annotations


BALANCE_LINES = [
    ("asset","Frais d'établissement"),
    ("asset","Immobilisations incorporelles"),
    ("asset","Frais de développement"),
    ("asset","Donations temporaires d’usufruit"),
    ("asset","Concessions, brevets, licences, marques, procédés, solutions informatiques, droits et valeurs similaires"),
    ("asset","Immobilisations incorporelles en cours, avances et acomptes"),
    ("asset","Immobilisations corporelles"),
    ("asset","Terrains"),
    ("asset","Constructions"),
    ("asset","Installations techniques, matériel et outillage industriels"),
    ("asset","Immobilisations corporelles en cours, avances et acomptes"),
    ("asset","Biens reçus par legs ou donations destinés à être cédés"),
    ("asset","Immobilisations financières"),
    ("asset","Participations"),
    ("asset","Créances rattachées à des participations"),
    ("asset","Autres titres immobilisés"),
    ("asset","Prêts"),
    ("asset","Autres immobilisations financières"),
    ("asset","Stocks et en-cours"),
    ("asset","Créances clients, usagers et comptes rattachés"),
    ("asset","Créances reçues par legs ou donations"),
    ("asset","Autres créances"),
    ("asset","Charges constatées d’avance"),
    ("asset","Valeurs mobilières de placement"),
    ("asset","Instruments financiers à terme et jetons détenus"),
    ("asset","Disponibilités"),
    ("asset","Frais d’émission des emprunts"),
    ("asset","Primes de remboursement des emprunts"),
    ("asset","Ecarts de conversion et différences d’évaluation Actif"),
    ("liability","Fonds propres sans droit de reprise"),
    ("liability","Fonds propres statutaires"),
    ("liability","Fonds propres complémentaires"),
    ("liability","Fonds propres avec droit de reprise"),
    ("liability","Ecarts de réévaluation"),
    ("liability","Réserves"),
    ("liability","Réserves statutaires ou contractuelles"),
    ("liability","Réserves pour projet de l’entité"),
    ("liability","Report à nouveau"),
    ("liability","Excédent ou déficit de l’exercice"),
    ("liability","Fonds propres consomptibles"),
    ("liability","Subventions d'investissement"),
    ("liability","Provisions réglementées"),
    ("liability","Fonds non remboursables"),
    ("liability","Avances conditionnées"),
    ("liability","Droits du concédant"),
    ("liability","Fonds reportés liés aux legs ou donations"),
    ("liability","Fonds dédiés"),
    ("liability","Provisions pour risques"),
    ("liability","Provisions pour charges"),
    ("liability","Emprunts obligataires et assimilés"),
    ("liability","Emprunts et dettes auprès des établissements de crédit"),
    ("liability","Emprunts et dettes financières diverses"),
    ("liability","Instruments financiers à terme"),
    ("liability","Dettes fournisseurs et comptes rattachés"),
    ("liability","Dettes des legs ou donations"),
    ("liability","Dettes fiscales et sociales"),
    ("liability","Dettes sur immobilisations et comptes rattachés"),
    ("liability","Autres dettes"),
    ("liability","Produits constatés d’avance"),
    ("liability","Ecarts de conversion et différences d’évaluation Passif"),
]

INCOME_LINES = [
    ("product","Cotisations"),
    ("product","Ventes de biens et services"),
    ("product","Ventes de biens"),
    ("product","dont ventes de dons en nature"),
    ("product","Ventes de prestations de service"),
    ("product","dont parrainages"),
    ("product","Produits de tiers financeurs"),
    ("product","Concours publics et subventions d'exploitation"),
    ("product","Versements des fondateurs ou consommations de la dotation consomptible"),
    ("product","Ressources liées à la générosité du public"),
    ("product","Dons manuels"),
    ("product","Mécénats"),
    ("product","Legs, donations et assurances-vie"),
    ("product","Contributions financières"),
    ("product","Reprises sur amortissements, dépréciations et provisions"),
    ("product","Produits des cessions d’immobilisations incorporelles et corporelles"),
    ("product","Utilisations des fonds dédiés"),
    ("product","Autres produits"),
    ("charge","Achats de marchandises"),
    ("charge","Variation de stock"),
    ("charge","Autres achats et charges externes"),
    ("charge","Aides financières"),
    ("charge","Impôts, taxes et versements assimilés"),
    ("charge","Salaires"),
    ("charge","Cotisations sociales"),
    ("charge","Dotations aux amortissements et aux dépréciations"),
    ("charge","Dotations aux provisions"),
    ("charge","Valeurs comptables des immobilisations incorporelles et corporelles cédées"),
    ("charge","Reports en fonds dédiés"),
    ("charge","Autres charges"),
    ("result","Résultat d'exploitation"),
    ("result","Résultat financier"),
    ("result","Résultat courant avant impôts"),
    ("product","Produits exceptionnels"),
    ("charge","Charges exceptionnelles"),
    ("result","Résultat exceptionnel"),
    ("charge","Participation des salariés aux résultats"),
    ("charge","Impôts sur les bénéfices"),
    ("result","Excédent ou déficit"),
    ("cvin_product","Dons en nature"),
    ("cvin_product","Prestations en nature"),
    ("cvin_product","Bénévolat"),
    ("cvin_charge","Secours en nature"),
    ("cvin_charge","Mises à disposition gratuite de biens"),
    ("cvin_charge","Prestations en nature"),
    ("cvin_charge","Personnel bénévole"),
]

CROD_LINES = [
    "Produits liés à la générosité du public",
    "Cotisations sans contrepartie",
    "Dons, legs et mécénat",
    "Dons manuels",
    "Legs, donations et assurances-vie",
    "Mécénat",
    "Autres produits liés à la générosité du public",
    "Produits non liés à la générosité du public",
    "Cotisations avec contrepartie",
    "Parrainage des entreprises",
    "Contributions financières sans contrepartie",
    "Autres produits non liés à la générosité du public",
    "Subventions et autres concours publics",
    "Reprises sur provisions et dépréciations",
    "Utilisations des fonds dédiés antérieurs",
    "Missions sociales",
    "Missions sociales réalisées en France",
    "Missions sociales réalisées à l’étranger",
    "Frais de recherche de fonds",
    "Frais d’appel à la générosité du public",
    "Frais de recherche d'autres ressources",
    "Frais de fonctionnement",
    "Dotations aux provisions et dépréciations",
    "Impôt sur les bénéfices",
    "Reports en fonds dédiés de l'exercice",
    "Excédent ou déficit",
]

CER_LINES = [
    "Missions sociales réalisées en France",
    "Missions sociales réalisées à l’étranger",
    "Frais d’appel à la générosité du public",
    "Frais de recherche d'autres ressources",
    "Frais de fonctionnement",
    "Total des emplois",
    "Dotations aux provisions et dépréciations",
    "Reports en fonds dédiés de l'exercice",
    "Excédent de la générosité du public de l’exercice",
    "Cotisations sans contrepartie",
    "Dons manuels",
    "Legs, donations et assurances-vie",
    "Mécénat",
    "Autres ressources liées à la générosité du public",
    "Total des ressources",
    "Reprises sur provisions et dépréciations",
    "Utilisations des fonds dédiés antérieurs",
    "Déficit de la générosité du public de l’exercice",
    "Ressources reportées liées à la générosité du public en début d'exercice",
    "Investissements et désinvestissements nets liés à la générosité du public de l'exercice",
    "Ressources reportées liées à la générosité du public en fin d'exercice",
    "Contributions volontaires aux missions sociales",
    "Contributions volontaires à la recherche de fonds",
    "Contributions volontaires au fonctionnement",
    "Contributions volontaires liées à la générosité du public",
    "Bénévolat",
    "Prestations en nature",
    "Dons en nature",
]


SPECIFIC_ACCOUNT_HINTS = {
    "Donations temporaires d’usufruit": ["204"],
    "Biens reçus par legs ou donations destinés à être cédés": ["24"],
    "Créances reçues par legs ou donations": ["461"],
    "Fonds propres sans droit de reprise": ["102"],
    "Fonds propres avec droit de reprise": ["103"],
    "Réserves pour projet de l’entité": ["1068"],
    "Fonds propres consomptibles": ["108"],
    "Fonds reportés liés aux legs ou donations": ["191"],
    "Fonds dédiés": ["194","195","196"],
    "Dettes des legs ou donations": ["466"],
    "Cotisations": ["756"],
    "dont ventes de dons en nature": ["7073"],
    "dont parrainages": ["7063"],
    "Versements des fondateurs ou consommations de la dotation consomptible": ["753"],
    "Ressources liées à la générosité du public": ["754"],
    "Dons manuels": ["7541"],
    "Mécénats": ["7542"],
    "Legs, donations et assurances-vie": ["7543"],
    "Contributions financières": ["755"],
    "Utilisations des fonds dédiés": ["789"],
    "Aides financières": ["657"],
    "Reports en fonds dédiés": ["689"],
    "Dons en nature": ["870"],
    "Bénévolat": ["875"],
    "Secours en nature": ["860"],
    "Mises à disposition gratuite de biens": ["861"],
    "Personnel bénévole": ["864"],
}


def _statement(statement_id, name, article_ref, source_pages, lines, line_mode="tuple"):
    out = []
    for idx, item in enumerate(lines, 1):
        if line_mode == "tuple":
            section, label = item
        else:
            section, label = "annex", item
        hints = SPECIFIC_ACCOUNT_HINTS.get(label, [])
        out.append({
            "line_id": f"{statement_id}:line:{idx:03d}",
            "line_code": f"L{idx:03d}",
            "label_source": label,
            "section": section,
            "account_hints": [{
                "account_prefix": code,
                "mapping_status": "derived_candidate_from_specific_nomenclature",
                "human_validation_required": True,
            } for code in hints],
        })
    return {
        "statement_id": statement_id,
        "name": name,
        "regulatory_article": article_ref,
        "source": {
            "document_id": "fr-nonprofit-recueil-2026-md",
            "page_start_pdf": source_pages[0],
            "page_end_pdf": source_pages[1],
        },
        "lines": out,
    }


def build_reporting() -> dict:
    statements = [
        _statement("nonprofit2026:balance", "Bilan non-lucratif", "421-1", (43,44), BALANCE_LINES),
        _statement("nonprofit2026:income", "Compte de résultat non-lucratif", "422-1", (45,46), INCOME_LINES),
        _statement("nonprofit2026:crod", "Compte de résultat par origine et destination", "432-2", (54,55), CROD_LINES, "list"),
        _statement("nonprofit2026:cer", "Compte d'emploi annuel des ressources collectées auprès du public", "432-17", (62,64), CER_LINES, "list"),
    ]
    return {
        "standard_id": "fr-nonprofit",
        "edition": "2026",
        "dataset_layer": "v3_reporting",
        "mapping_policy": {
            "statement_structure": "official_source",
            "account_hints": "derived_candidate",
            "account_hints_executable": False,
            "human_validation_required": True,
        },
        "statements": statements,
        "statistics": {
            "statement_templates": len(statements),
            "statement_lines": sum(len(s["lines"]) for s in statements),
            "lines_with_account_hints": sum(bool(l["account_hints"]) for s in statements for l in s["lines"]),
        },
    }
